language: csharp
solution: ./LennyBOT.sln
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - dotnet restore -s https://www.myget.org/F/discord-net/api/v3/index.json
  - dotnet publish -r ubuntu.16.04-x64
