language: csharp
solution: ./LennyBOT.sln
dist: trusty
mono: none
dotnet: 2.0.0
script:
  - nuget sources Add -Name "DiscordNet" -Source https://www.myget.org/F/discord-net/api/v3/index.json
  - nuget restore ./LennyBOT.sln
  - dotnet restore
  - dotnet publish -r ubuntu.16.04-x64
